export enum INPUT_ACTION_TYPES {
  SELECT_INPUT_TAB = '[INPUT] - SELECT_INPUT_TAB',
  SELECT_OUTPUT_TAB = '[INPUT] - SELECT_OUTPUT_TAB',
  REVERSE_TABS = '[INPUT] - REVERSE_TABS',

  CHANGE_INPUT = '[INPUT] - CHANGE_INPUT',
  CHANGE_OUTPUT = '[INPUT] - CHANGE_OUTPUT',
  CHANGE_INPUT_EXCHANGE_COURSE = '[INPUT] - CHANGE_INPUT_EXCHANGE_COURSE',
  CHANGE_OUTPUT_EXCHANGE_COURSE = '[INPUT] - CHANGE_OUTPUT_EXCHANGE_COURSE',
}
