export enum CONVERTER_ACTION_TYPES {
  SELECT_INPUT_TAB = '[CONVERTER] - SELECT_INPUT_TAB',
  SELECT_OUTPUT_TAB = '[CONVERTER] - SELECT_OUTPUT_TAB',
  REVERSE_TABS = '[CONVERTER] - REVERSE_TABS',

  CHANGE_INPUT = '[CONVERTER] - CHANGE_INPUT',
  CHANGE_OUTPUT = '[CONVERTER] - CHANGE_OUTPUT',
  CHANGE_INPUT_EXCHANGE_COURSE = '[CONVERTER] - CHANGE_INPUT_EXCHANGE_COURSE',
  CHANGE_OUTPUT_EXCHANGE_COURSE = '[CONVERTER] - CHANGE_OUTPUT_EXCHANGE_COURSE',
}
